staticfiles:
    build: /srv/systemuser
    command: echo "#data-container-hack"
    volumes:
    - "{{ notebook_static_files }}"

nginx:
    build: /srv/nginx
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - letsencrypt:/etc/letsencrypt
      - letsencrypt-backups:/var/lib/letsencrypt
      - dhparam-cache:/cache
    volumes_from:
      - staticfiles
    environment:
      EMAIL: jessica.b.hamrick@gmail.com
      DOMAIN: compmodels.tmpnb.org
      UPSTREAM: {{ jupyterhub_host }}:8000
      # STAGING: 1
