---
- name: clone the dockerfile git repository
  git: repo=https://github.com/compmodels/systemuser.git dest=/srv/systemuser

- name: configuration directories
  file: state=directory dest=/srv/nginx mode=0755

- name: docker volumes for let's encrypt
  command: docker volume create --name {{ item }}
  with_items:
    - letsencrypt
    - letsencrypt-backups
    - dhparam-cache

- name: nginx configuration
  template: src=nginx.conf.j2 dest=/srv/nginx/nginx.conf mode=0644

- name: nginx vhost configuration
  template: src=vhost.sample.conf.j2 dest=/srv/nginx/vhost.sample.conf mode=0644

- name: copy the Dockerfile to the nginx configuration directory
  template: src=Dockerfile.j2 dest=/srv/nginx/Dockerfile mode=0644

- name: install docker-compose.yml
  template: src=docker-compose.yml dest=/root/docker-compose.yml

- name: stop docker containers
  command: docker-compose stop

- name: remove docker containers
  command: docker-compose rm -f

- name: pull docker images
  command: docker-compose pull

- name: build docker images
  command: docker-compose build

- name: start services
  command: docker-compose up -d
